name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2:00 AM UTC
  workflow_dispatch:
    inputs:
      keep_minimum_runs:
        description: 'Number of workflow runs to keep'
        required: false
        default: '5'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: ${{ github.event.inputs.keep_minimum_runs || 5 }}
